"""Convert a meeting briefing JSON artifact to a PDF via pandoc + xelatex."""

import json
import subprocess
import sys
import tempfile
from pathlib import Path


def json_to_markdown(data: dict) -> str:
    eo = data["eo"]
    m = data["meeting"]
    s = data["score"]

    lines = [
        "---",
        "geometry: margin=1in",
        "fontsize: 11pt",
        "mainfont: Helvetica",
        "---",
        "",
        f'# Meeting Briefing: {eo["name"]}',
        f'**{eo.get("office", "City Council")} · {eo["city"]}, {eo["state"]}**',
        "",
        f'**Meeting:** {m["body"]} · {m["date"]} at {m.get("time", "TBD")}',
        f'**Score:** {s["total"]}/{s["max"]} · Recommendation: **{s["recommendation"].upper()}**',
        "",
        "---",
        "",
        "# Teaser Email",
        "",
        data["teaser_email"],
        "",
        "---",
        "",
        "# Full Briefing",
        "",
    ]

    for line in data["briefing_content"].split("\n"):
        if line.startswith("# "):
            lines.append("##" + line[1:])
        elif line.startswith("## "):
            lines.append("###" + line[2:])
        else:
            lines.append(line)

    lines.extend([
        "",
        "---",
        "",
        "# Score Breakdown",
        "",
        f'**Total: {s["total"]}/{s["max"]}**',
        "",
        "| Dimension | Score | Justification |",
        "|-----------|-------|---------------|",
    ])
    for dim in s["dimensions"]:
        just = dim.get("justification", "").replace("|", "/").replace("\n", " ")[:120]
        lines.append(f'| {dim["name"]} | {dim["score"]}/10 | {just} |')

    lines.extend([
        "",
        "---",
        "",
        "# Data Sources",
        "",
        "| ID | Type | Title |",
        "|----|------|-------|",
    ])
    for src in data.get("sources", []):
        title = src.get("title", "").replace("|", "/").replace("\n", " ")[:80]
        stype = src.get("type", "").replace("_", " ")
        lines.append(f"| {src['id']} | {stype} | {title} |")

    lines.extend([
        "",
        "---",
        "",
        "*Generated by GoodParty.org PMF Engine*",
    ])

    return "\n".join(lines)


def main():
    if len(sys.argv) < 2:
        print("Usage: uv run python briefing_to_pdf.py <input.json> [output.pdf] [--pdf-engine=ENGINE]")
        print("  ENGINE defaults to xelatex. Use pdflatex or lualatex if xelatex is unavailable.")
        sys.exit(1)

    input_path = Path(sys.argv[1])
    output_path = Path(sys.argv[2]) if len(sys.argv) > 2 and not sys.argv[2].startswith("--") else input_path.with_suffix(".pdf")

    engine = "xelatex"
    for arg in sys.argv[2:]:
        if arg.startswith("--pdf-engine="):
            engine = arg.split("=", 1)[1]

    data = json.loads(input_path.read_text())
    md = json_to_markdown(data)

    with tempfile.NamedTemporaryFile(suffix=".md", mode="w", delete=False) as f:
        f.write(md)
        md_path = f.name

    try:
        subprocess.run(
            [
                "pandoc", md_path,
                "-o", str(output_path),
                f"--pdf-engine={engine}",
                "-V", "geometry:margin=1in",
                "-V", "fontsize=11pt",
                "-V", "mainfont=Helvetica",
            ],
            check=True,
            capture_output=True,
            text=True,
        )
        print(f"PDF written to {output_path} ({output_path.stat().st_size // 1024}KB)")
    except subprocess.CalledProcessError as e:
        print(f"pandoc failed: {e.stderr}", file=sys.stderr)
        sys.exit(1)
    finally:
        Path(md_path).unlink(missing_ok=True)


if __name__ == "__main__":
    main()
