"""Convert a meeting briefing JSON artifact to a PDF via pandoc + xelatex."""

import json
import subprocess
import sys
import tempfile
from pathlib import Path


def build_footnote_map(sources: list) -> dict:
    """Return {source_id: index} for all sources, 1-based."""
    return {src["id"]: i + 1 for i, src in enumerate(sources)}


def apply_footnotes(text: str, fn_map: dict) -> str:
    """Replace [source-id] markers with pandoc footnote references [^N]."""
    import re
    def replace(m):
        sid = m.group(1)
        return f"[^{fn_map[sid]}]" if sid in fn_map else m.group(0)
    return re.sub(r'\[([a-z0-9_-]+)\]', replace, text)


def footnote_definitions(sources: list) -> list:
    """Return pandoc footnote definition lines for each source."""
    lines = []
    for i, src in enumerate(sources):
        n = i + 1
        type_label = src.get("type", "").replace("_", " ").title()
        title = src.get("title", "")
        url = src.get("url", "")
        lines.append(f"[^{n}]: *{type_label}.* {title}. <{url}>")
    return lines


def json_to_markdown(data: dict) -> str:
    eo = data["eo"]
    m = data["meeting"]
    s = data["score"]
    sources = data.get("sources", [])
    fn_map = build_footnote_map(sources)

    lines = [
        "---",
        "geometry: margin=1in",
        "fontsize: 11pt",
        "mainfont: Helvetica",
        "---",
        "",
        f'# Meeting Briefing: {eo["name"]}',
        f'**{eo.get("office", "City Council")} · {eo["city"]}, {eo["state"]}**',
        "",
        f'**Meeting:** {m["body"]} · {m["date"]} at {m.get("time", "TBD")}',
        f'**Score:** {s["total"]}/{s["max"]} · Recommendation: **{s["recommendation"].upper()}**',
        "",
        "---",
        "",
        "# Teaser Email",
        "",
        data["teaser_email"],
        "",
        "---",
        "",
        "# Full Briefing",
        "",
    ]

    briefing_with_footnotes = apply_footnotes(data["briefing_content"], fn_map)
    for line in briefing_with_footnotes.split("\n"):
        if line.startswith("# "):
            lines.append("##" + line[1:])
        elif line.startswith("## "):
            lines.append("###" + line[2:])
        else:
            lines.append(line)

    lines.append("")
    lines.extend(footnote_definitions(sources))

    lines.extend([
        "",
        "---",
        "",
        "# Score Breakdown",
        "",
        f'**Total: {s["total"]}/{s["max"]}**',
        "",
        "| Dimension | Score | Justification |",
        "|-----------|-------|---------------|",
    ])
    for dim in s["dimensions"]:
        just = dim.get("justification", "").replace("|", "/").replace("\n", " ")[:120]
        lines.append(f'| {dim["name"]} | {dim["score"]}/10 | {just} |')

    lines.extend([
        "",
        "---",
        "",
        "# Data Sources",
        "",
        "| ID | Type | Title |",
        "|----|------|-------|",
    ])
    for src in data.get("sources", []):
        title = src.get("title", "").replace("|", "/").replace("\n", " ")[:80]
        stype = src.get("type", "").replace("_", " ")
        lines.append(f"| {src['id']} | {stype} | {title} |")

    lines.extend([
        "",
        "---",
        "",
        "*Generated by GoodParty.org PMF Engine*",
    ])

    return "\n".join(lines)


def main():
    if len(sys.argv) < 2:
        print("Usage: uv run python briefing_to_pdf.py <input.json> [output.pdf]")
        sys.exit(1)

    input_path = Path(sys.argv[1])
    output_path = Path(sys.argv[2]) if len(sys.argv) > 2 else input_path.with_suffix(".pdf")

    data = json.loads(input_path.read_text())
    md = json_to_markdown(data)

    with tempfile.NamedTemporaryFile(suffix=".md", mode="w", delete=False) as f:
        f.write(md)
        md_path = f.name

    try:
        subprocess.run(
            [
                "pandoc", md_path,
                "-o", str(output_path),
                "--pdf-engine=xelatex",
                "-V", "geometry:margin=1in",
                "-V", "fontsize=11pt",
                "-V", "mainfont=Helvetica",
            ],
            check=True,
            capture_output=True,
            text=True,
        )
        print(f"PDF written to {output_path} ({output_path.stat().st_size // 1024}KB)")
    except subprocess.CalledProcessError as e:
        print(f"pandoc failed: {e.stderr}", file=sys.stderr)
        sys.exit(1)
    finally:
        Path(md_path).unlink(missing_ok=True)


if __name__ == "__main__":
    main()
