"""Convert a voter targeting JSON artifact to a PDF via pandoc + xelatex."""

import json
import subprocess
import sys
import tempfile
from pathlib import Path


def json_to_markdown(data: dict) -> str:
    district = data.get("district", {})
    summary = data["summary"]
    segments = data["segments"]

    city = district.get("city") or district.get("l2_name", "")
    state = district.get("state", "")
    office = district.get("name", "")

    lines = [
        f"# Voter Targeting: {city}, {state}",
        f"**Office:** {office}",
        "",
        f"**Generated:** {data.get('generated_at', 'N/A')[:10]}",
        "",
        "---",
        "",
        "## Campaign Math",
        "",
        "| Metric | Value |",
        "|--------|-------|",
        f"| Total Voters in District | {summary['total_voters_in_district']:,} |",
        f"| Win Number | {summary['win_number']:,} |",
        f"| Projected Turnout | {summary['projected_turnout']:,} |",
        "",
        "---",
        "",
        "## Segment Overview",
        "",
        "| Tier | Segment | Voters | Priority | Channels |",
        "|------|---------|--------|----------|----------|",
    ]

    for s in segments:
        channels = ", ".join(s.get("recommended_channels", []))[:40]
        priority = s.get("outreach_priority", "")
        lines.append(
            f"| {s['tier']} | {s['name']} | {s['count']:,} | {priority} | {channels} |"
        )

    lines.extend(["", "---", "", "## Methodology", "", data.get("methodology", "N/A"), ""])

    # Detail pages per segment
    for s in segments:
        lines.extend(["\\newpage", "", f"## Tier {s['tier']}: {s['name']}", ""])

        lines.append(f"**{s['count']:,} voters** · Priority: **{s.get('outreach_priority', 'N/A')}**")
        lines.append("")

        channels = s.get("recommended_channels", [])
        if channels:
            lines.append(f"**Recommended Channels:** {', '.join(channels)}")
            lines.append("")

        # Demographics
        demo = s.get("demographics", {})
        party = demo.get("party_breakdown", {})
        age = demo.get("age_distribution", {})
        gender = demo.get("gender_split", {})

        if party:
            lines.extend([
                "### Party Breakdown",
                "",
                "| Party | Count | % |",
                "|-------|-------|---|",
            ])
            total = sum(party.values())
            for p, count in sorted(party.items(), key=lambda x: -x[1]):
                pct = f"{count / total * 100:.1f}" if total else "0"
                lines.append(f"| {p} | {count:,} | {pct}% |")
            lines.append("")

        if age:
            lines.extend([
                "### Age Distribution",
                "",
                "| Age Group | Count | % |",
                "|-----------|-------|---|",
            ])
            total = sum(age.values())
            for a, count in sorted(age.items()):
                pct = f"{count / total * 100:.1f}" if total else "0"
                lines.append(f"| {a} | {count:,} | {pct}% |")
            lines.append("")

        if gender:
            lines.extend([
                "### Gender Split",
                "",
                "| Gender | Count | % |",
                "|--------|-------|---|",
            ])
            total = sum(gender.values())
            for g, count in sorted(gender.items(), key=lambda x: -x[1]):
                pct = f"{count / total * 100:.1f}" if total else "0"
                lines.append(f"| {g} | {count:,} | {pct}% |")
            lines.append("")

        # Sample voters
        voters = s.get("voters", [])
        if voters:
            lines.extend([
                f"### Sample Voters (showing {min(30, len(voters))} of {len(voters):,})",
                "",
                "| # | Name | Address | City | Party | Age |",
                "|---|------|---------|------|-------|-----|",
            ])
            for i, v in enumerate(voters[:30], 1):
                name = f"{v.get('first_name', '')} {v.get('last_name', '')}".strip()[:20]
                addr = (v.get("address") or "")[:25].replace("|", "/")
                vcity = (v.get("city") or "")[:15]
                party = (v.get("party") or "")[:12]
                age_v = v.get("age", "")
                lines.append(f"| {i} | {name} | {addr} | {vcity} | {party} | {age_v} |")

            if len(voters) > 30:
                lines.append(f"| | *... {len(voters) - 30:,} more voters* | | | | |")
            lines.append("")

    lines.extend(["---", "", "*Generated by GoodParty.org PMF Engine*"])
    return "\n".join(lines)


def main():
    if len(sys.argv) < 2:
        print("Usage: uv run python voter_targeting_to_pdf.py <input.json> [output.pdf]")
        sys.exit(1)

    input_path = Path(sys.argv[1])
    output_path = (
        Path(sys.argv[2])
        if len(sys.argv) > 2 and not sys.argv[2].startswith("--")
        else input_path.with_suffix(".pdf")
    )

    engine = "xelatex"
    for arg in sys.argv[2:]:
        if arg.startswith("--pdf-engine="):
            engine = arg.split("=", 1)[1]

    data = json.loads(input_path.read_text())
    md = json_to_markdown(data)

    with tempfile.NamedTemporaryFile(suffix=".md", mode="w", delete=False) as f:
        f.write(md)
        md_path = f.name

    try:
        subprocess.run(
            [
                "pandoc", md_path,
                "-o", str(output_path),
                f"--pdf-engine={engine}",
                "-V", "geometry:margin=0.75in",
                "-V", "fontsize=10pt",
                "-V", "mainfont=Helvetica",
            ],
            check=True,
            capture_output=True,
            text=True,
        )
        print(f"PDF written to {output_path} ({output_path.stat().st_size // 1024}KB)")
    except subprocess.CalledProcessError as e:
        print(f"pandoc failed: {e.stderr}", file=sys.stderr)
        sys.exit(1)
    finally:
        Path(md_path).unlink(missing_ok=True)


if __name__ == "__main__":
    main()
