"""Convert a walking plan JSON artifact to a PDF via pandoc + xelatex."""

import json
import subprocess
import sys
import tempfile
from pathlib import Path


def json_to_markdown(data: dict) -> str:
    district = data.get("district", {})
    summary = data["summary"]
    areas = data["areas"]

    city = district.get("l2_name") or district.get("name", "")
    state = district.get("state", "")
    office = district.get("name", "")

    lines = [
        "",
        f"# Walking Plan: {city}, {state}",
        f"**Office:** {office}",
        "",
        f"**Generated:** {data.get('generated_at', 'N/A')[:10]}",
        "",
        "---",
        "",
        "## Summary",
        "",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| Total Areas | {summary['total_areas']} |",
        f"| Total Doors | {summary['total_doors']:,} |",
        f"| Est. Total Hours | {summary['estimated_total_hours']} |",
        f"| Top Issues | {', '.join(summary.get('top_issues', []))} |",
        "",
        "---",
        "",
        "## Methodology",
        "",
        data.get("methodology", "N/A"),
        "",
        "\\newpage",
        "",
        "## Areas Overview",
        "",
        "| # | Area | Doors | Est. Min | Priority |",
        "|---|------|-------|----------|----------|",
    ]

    for i, area in enumerate(areas[:50], 1):
        name = area["name"].replace("|", "/")[:30]
        lines.append(
            f"| {i} | {name} | {area['door_count']} "
            f"| {area['estimated_minutes']} | {area.get('priority_rank', i)} |"
        )

    if len(areas) > 50:
        lines.append(f"| | *... {len(areas) - 50} more areas* | | | |")

    lines.extend(["", "\\newpage", ""])

    # Detail pages for top 20 areas
    for i, area in enumerate(areas[:20], 1):
        name = area["name"]
        lines.extend([
            f"## Area {i}: {name}",
            "",
            f"**Doors:** {area['door_count']} · "
            f"**Est. Time:** {area['estimated_minutes']} min · "
            f"**Priority:** {area.get('priority_rank', i)}",
            "",
        ])

        breakdown = area.get("party_breakdown", {})
        if breakdown:
            parts = [f"{k}: {v}" for k, v in sorted(breakdown.items(), key=lambda x: -x[1])]
            lines.append(f"**Party Mix:** {', '.join(parts)}")
            lines.append("")

        maps_url = area.get("maps_url", "")
        if maps_url:
            lines.append(f"**Maps:** [Open in Google Maps]({maps_url})")
            lines.append("")

        voters = area.get("voters", [])
        if voters:
            lines.extend([
                "| # | Name | Address | Party | Age | Key Talking Point |",
                "|---|------|---------|-------|-----|-------------------|",
            ])
            for v in voters[:40]:
                name_v = v.get("voter_name", "").replace("|", "/")[:20]
                addr = v.get("address", "").replace("|", "/")[:25]
                party = v.get("party", "")[:12]
                age = v.get("age", "")
                tp = v.get("talking_points", [""])[0][:50].replace("|", "/") if v.get("talking_points") else ""
                lines.append(f"| {v.get('order', '')} | {name_v} | {addr} | {party} | {age} | {tp} |")

            if len(voters) > 40:
                lines.append(f"| | *... {len(voters) - 40} more voters* | | | | |")

        lines.extend(["", "\\newpage", ""])

    lines.extend([
        "---",
        "",
        "*Generated by GoodParty.org PMF Engine*",
    ])

    return "\n".join(lines)


def main():
    if len(sys.argv) < 2:
        print("Usage: uv run python walking_plan_to_pdf.py <input.json> [output.pdf]")
        sys.exit(1)

    input_path = Path(sys.argv[1])
    output_path = (
        Path(sys.argv[2])
        if len(sys.argv) > 2 and not sys.argv[2].startswith("--")
        else input_path.with_suffix(".pdf")
    )

    engine = "xelatex"
    for arg in sys.argv[2:]:
        if arg.startswith("--pdf-engine="):
            engine = arg.split("=", 1)[1]

    data = json.loads(input_path.read_text())
    md = json_to_markdown(data)

    with tempfile.NamedTemporaryFile(suffix=".md", mode="w", delete=False) as f:
        f.write(md)
        md_path = f.name

    try:
        subprocess.run(
            [
                "pandoc", md_path,
                "-o", str(output_path),
                f"--pdf-engine={engine}",
                "-V", "geometry:margin=0.75in",
                "-V", "fontsize=10pt",
                "-V", "mainfont=Helvetica",
            ],
            check=True,
            capture_output=True,
            text=True,
        )
        print(f"PDF written to {output_path} ({output_path.stat().st_size // 1024}KB)")
    except subprocess.CalledProcessError as e:
        print(f"pandoc failed: {e.stderr}", file=sys.stderr)
        sys.exit(1)
    finally:
        Path(md_path).unlink(missing_ok=True)


if __name__ == "__main__":
    main()
